[package]
name = "file-upload-server"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
askama = "0.15.4"
axum = "0.8.8"
lazy_static = "1.5.0"
tokio = { version = "1.49.0", features = ["full"] }
